module.exports = {
  apps: [
    {
      name: 'dramz-backend',
      script: 'node dist/src/main.js',
      cwd: '/root/dramz-new/backend',
      instances: 1,
      exec_mode: 'fork',
      interpreter: 'node',
      interpreter_args: '',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      error_file: '/root/.pm2/logs/dramz-backend-error.log',
      out_file: '/root/.pm2/logs/dramz-backend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_memory_restart: '1G',
      watch: false,
    },
    {
      name: 'dramz-frontend',
      script: 'npm',
      args: 'start',
      cwd: '/root/dramz-new/frontend/dramz',
      instances: 1,
      exec_mode: 'fork',
      interpreter: 'node',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
      },
      error_file: '/root/.pm2/logs/dramz-frontend-error.log',
      out_file: '/root/.pm2/logs/dramz-frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_memory_restart: '1G',
      watch: false,
    },
    {
      name: 'dramz-admin',
      script: 'npm',
      args: 'start',
      cwd: '/root/dramz-new/frontend/dramz-admin',
      instances: 1,
      exec_mode: 'fork',
      interpreter: 'node',
      env: {
        NODE_ENV: 'production',
        PORT: 3002,
      },
      error_file: '/root/.pm2/logs/dramz-admin-error.log',
      out_file: '/root/.pm2/logs/dramz-admin-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_memory_restart: '1G',
      watch: false,
    },
  ],
};

