import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import TelegramInit from "./telegram-init";
import Providers from "./providers";
import { cookies } from "next/headers";
import ModalRoot from "./components/ModalRoot";
import PageLayout from "./components/PageLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  viewportFit: "cover",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies()
  const tgCookie = cookieStore.get('tgUser') || null
  const initialUser = tgCookie ? JSON.parse(tgCookie.value) : null
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Script src="https://telegram.org/js/telegram-web-app.js" strategy="afterInteractive" />
        <TelegramInit />
        <Providers initialUser={initialUser}>
          <PageLayout>
            {children}
          </PageLayout>
          <ModalRoot />
        </Providers>
      </body>
    </html>
  );
}
